[package]
name = "hackmd"
version = "0.0.1"
edition = "2024"
description = "Rust client library and CLI for HackMD"
license = "MIT"
repository = "https://github.com/zemse/hackmd-rs"
readme = "README.md"
keywords = ["hackmd", "markdown", "cli", "tui", "api"]
categories = ["api-bindings", "command-line-utilities"]
include = [
    "/src/**/*.rs",
    "/README.md",
    "/LICENSE*",
]

[lib]
name = "hackmd"
path = "src/lib.rs"

[[bin]]
name = "hackmd"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = []
tui = ["cli"]

[dependencies]

[dev-dependencies]
